// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WeightDBContext))]
    [Migration("20260913100328_AddUserTerminalModeOverride")]
    partial class AddUserTerminalModeOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.Audit.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("Core.Domain.Entities.Behaviors.ExternalTargetBehavior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlmacenName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetAlmacen")
                        .HasColumnType("text");

                    b.Property<string>("TargetConcept")
                        .HasColumnType("text");

                    b.Property<string>("TargetDomain")
                        .HasColumnType("text");

                    b.Property<string>("TargetName")
                        .HasColumnType("text");

                    b.Property<string>("TargetSerie")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExternalTargetBehaviors");
                });

            modelBuilder.Entity("Core.Domain.Entities.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CanCaptureWeightManuallyOverride")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanSelfAuthorizeGateOverride")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InactivityTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int?>("TerminalModeOverride")
                        .HasColumnType("integer");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Domain.Entities.ProviderOrders.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpectedArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Core.Domain.Entities.ProviderOrders.PedidoLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ManuallyClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RequiredAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("RequiresDisTaring")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoLines");
                });

            modelBuilder.Entity("Core.Domain.Entities.Turns.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("WeightEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Core.Domain.Entities.Weight.WeightDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Costales")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FK_PedidoLineId")
                        .HasColumnType("integer");

                    b.Property<int>("FK_WeightEntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("FK_WeightedProductId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double?>("ProductPrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("RequiredAmount")
                        .HasColumnType("double precision");

                    b.Property<double?>("SecondaryTare")
                        .HasColumnType("double precision");

                    b.Property<double>("Tare")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<string>("WeightedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FK_PedidoLineId");

                    b.HasIndex("FK_WeightEntryId");

                    b.ToTable("WeightDetails");
                });

            modelBuilder.Entity("Core.Domain.Entities.Weight.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BruteWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ConcludeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConptaqiComercialFK")
                        .HasColumnType("integer");

                    b.Property<string>("ContpaqiComercialFolio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExternalTargetBehaviorFK")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDischarge")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<string>("RegisteredBy")
                        .HasColumnType("text");

                    b.Property<double>("TareWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTargetBehaviorFK");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("Core.Domain.Entities.ProviderOrders.PedidoLine", b =>
                {
                    b.HasOne("Core.Domain.Entities.ProviderOrders.Pedido", "Pedido")
                        .WithMany("Lines")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Core.Domain.Entities.Weight.WeightDetail", b =>
                {
                    b.HasOne("Core.Domain.Entities.ProviderOrders.PedidoLine", "PedidoLine")
                        .WithMany("WeightDetails")
                        .HasForeignKey("FK_PedidoLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Domain.Entities.Weight.WeightEntry", "WeightEntry")
                        .WithMany("WeightDetails")
                        .HasForeignKey("FK_WeightEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoLine");

                    b.Navigation("WeightEntry");
                });

            modelBuilder.Entity("Core.Domain.Entities.Weight.WeightEntry", b =>
                {
                    b.HasOne("Core.Domain.Entities.Behaviors.ExternalTargetBehavior", "ExternalTargetBehavior")
                        .WithMany()
                        .HasForeignKey("ExternalTargetBehaviorFK");

                    b.Navigation("ExternalTargetBehavior");
                });

            modelBuilder.Entity("Core.Domain.Entities.ProviderOrders.Pedido", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Core.Domain.Entities.ProviderOrders.PedidoLine", b =>
                {
                    b.Navigation("WeightDetails");
                });

            modelBuilder.Entity("Core.Domain.Entities.Weight.WeightEntry", b =>
                {
                    b.Navigation("WeightDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
